<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TIKSN.smite.lib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SerializationModels.fs" />
    <Compile Include="CommonFeatures.fs" />
    <Compile Include="IndentationFeatures.fs" />
    <Compile Include="TypeScriptTranspiler.fs" />
    <Compile Include="FSharpTranspiler.fs" />
    <Compile Include="RoslynTranspiler.fs" />
    <Compile Include="VisualBasicTranspiler.fs" />
    <Compile Include="CSharpTranspiler.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="Saving.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.11.0" />
    <PackageReference Include="TIKSN-Framework" Version="5.4.3" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.101" />
  </ItemGroup>

</Project>
